name: shabsrajan
favicon: null
layout_spectrum: 0.07893395749852061
typography_spectrum: 0.39561325986869633
title: "impact investing, dementia care and other stuff that's not very interesting"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
