name: shabsrajan
favicon: null
layout_spectrum: 0.07893395749852061
typography_spectrum: 0.39561325986869633
title: "impact investing, dementia care and other stuff that's not very interesting"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fa6900'
    - '#f38630'
    - '#e0e4cc'
    - '#a7dbd8'
    - '#69d2e7'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
